name: Android CI/CD

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@f0d2c42d7b04ed2c87b8d6b153890ee10c0ddfd1
      with:
        fileName: 'scheduling_assistant.jks'
        fileDir: './app/'
        encodedString: ${{ secrets.SIGNING_KEY }}
      
    - name: Build Release APK
      env:
        SIGNING_STORE_FILE: scheduling_assistant.jks
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease
        
    - name: Create Release
      uses: softprops/action-gh-release@2d279924e1f8c4398fca6d1d63dbe6e7f6f0e693
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app/build/outputs/apk/release/app-release.apk
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          Release ${{ github.ref_name }}
          
          Changes in this release:
          - Automated build from master branch
          - See commit history for details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
